name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  echo-checkout:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a pen"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
